module.exports.categories =[
'Welding',
'Electrician',
'Plumbing',
'Carpentry',
'Construction management',
'Pipe-fitting',
'Machining',
'Computer-aided drafting',
'Network administration',
'Civil engineering tech',
'Hair dresser',
'Tailor',
'Biomedical engineering',
'Goldsmith',
'Gem cutter',
'Photography',
'Barbers',
'Steel erecting',
'Welding',
'Boilermaking',
'Millwright',
'Blacksmith',
'Gunsmith',
'Marquetarian',
'Farrier',
'Furniture making',
'Pewterer',
'Damascener',
'Laptop repair',
'Phone repair',
'Shoemaking',
'Massage',
'Watch repair',
'Catering',
'Printing',
'Generator repair',
'Chauffeur',
'Vigilante',
'Plumbing machine repair',
'Freezer repair'
]

module.exports.hotels = [
    'Hypnos'
    ,'Iris'
    ,'Azul'
    ,'Ebony'
    ,'Altheda'
    ,'Aurelia'
    ,'Citrus'
    ,'The Nectarine'
    ,'Xanthe'
    ,'Saros'
    ,'Odyssey Resort'
    ,'7 Mirrors Hotel'
    ,'Aether' 
    ,'Primrose High'
    ,'Ceilo '
    ,'Dritan Stay'
    ,'Eight Foot'
    ,'Jade Hotel '
    ,'Gaia'
    ,'Indigo' 
    ,'25 Hazel' 
    ,'Melanie'
    ,'Truth Hotel'
    ,'Beatrix'
    ,'The Gregory'
    ,'Tangerine'
    ,'Columba '
    ,'Blue Jay Hotel'
    ,'Ignite Hotel'
    ,'New Apollo'
    ,'Pearl Lodge'
    ,'Cider'
    ,'Sequoia Hotel'
    ,'Olive Garden'
    ,'Maple 247'
    ,'Cedar Point'
    ,'Gazella'
    ,'101 Clover'
    ,'Hazelwood Hotel'
    ,'Alyvia'
    ,'Stargaze Inn'
    ,'Seek Safari'
    ,'Blizzard (blizzardhotel.com)'
    ,'Stardust Cabin'
    ,'Atlas Hotel'
    ,'Panthera'
    ,'Atlas Villa (atlasvilla.com)'
    ,'Hesperus '
    ,'The Jasmine Hotel'
    ,'Voltage Hotel'
    ,'El Arturo'
    ,'Giselle Hotel'
    ,'Blaise Hotel '
    ,'Stamp Hotel'
    ,'Antheia '
    ,'Saffron '
    ,'New Age Hotel'
    ,'Calantha Hotel '
    ,'Emerald '
    ,'The Antonio (antoniohotel.com)'
    ,'Emerge Hotel'
    ,'The Sandcastle'
    ,'Helios Beach Resort'
    ,'Nereus Villa'
    ,'Mazarin'
    ,'99 Beach House'
    ,'Mobi Beach'
    ,'Aqiuos'
    ,'Coast Casa'
    ,'Azure Inn'
    ,'Celeste Hotel'
    ,'Coconut Hotel'
    ,'Casa Juan (casa-juan.com!)'
    ,'Amistad'
    ,'Palmones'
    ,'Sandize'
    ,'Hammockes'
    ,'Soft Hammock'
    ,'The Breeze Bay'
    ,'Flipflop Stay'
    ,'Sandbank Villa'
    ,'Beachgrass'
    ,'The Banana Bay or Banana Bai'
    ,'Whistling Waters'
    ,'Pelican Town'
    ,'Crowne Plaza'
    ,'Emerald Bay Inn'
    ,'Hotel Bliss'
    ,'University Inn'
    ,'The New View'
    ,'Ramada Limited & Suites'
    ,'Sunset Lodge'
    ,'Hotel Elite'
    ,'Lake Place Inn'
    ,'Beacon Motel'
    ,'Comfort B&B'
    ,'The Fresco Hotel'
    ,'Motel On Main'
    ,'Holly House'
    ,'High Desert Inn'
    ,'Four Seasons'
    ,'Budget Suites'
    ,'American Inn'
    ,'Relax Inn'
    ,'Golden Cherry Motel'
    ,'Sapphires Hotel'
    ,'The Glory Hotel'
    ,'Friendship Inn'
    ,'Time Motel'
    ,'The Breakers'
    ,'The Venetian'
    ,'Spotlight Hotel'
    ,'The Mississippi Hotel'
    ,'Green Tortoise Hostel'
    ,'The Orchard Hotel'
    ,'Spring Brook'
    ,'Hotel Agoura'
    ,'Wonder Hill Inn'
    ,'The New Yorker'
    ,'Beachwalk Resort'
    ,'Etiquette Suites'
    ,'Water Vibe Resorts'
    ,'Consulate Hotel'
    ,'Quaint Motel'
    ,'Cape Grace'
    ,'Fountain Fun'
    ,'Element'
    ,'The New View'
    ,'White Season Resort'
    ,'Hotel Occazia'
    ,'Purple Orchid'
    ,'Prestige proga Inn'
    ,'The Manhattan'
    ,'Lime Wood'
    ,'Parallel Shine'

    ,'The Glory Hotel'
    ,'The Mutiny Hotel'
    ,'The Huntington Hotel'
    ,'Towne Place Suites'
    ,'Cosmopolitan Hotel'
    ,'Eden Roc'
    ,'Coastal bay hotel'
    ,'Dream Connect'
    ,'Purple Orchid'
    ,'The Palazzo Resort'
    ,'The White Rock Hotel'
    ,'The Hot Springs Hotel'
    ,'Venture Hotel'
    ,'The Lakefront'
    ,'The Peninsula'
    ,'The Lakefront'
    ,'Always Welcome'
    ,'Tower Hotel'
    ,'Sunny Canopy'
    ,'Royal Galaxy'
    ,'The Watson Hotel'
    ,'Treebones Resort'
    ,'Waypoint'
    ,'The Eternity Resort'
    ,'Sandy Bloom'


,'String Hotel'
,'Comfort Inn'
,'Cable Car Hotel'
,'Trance Hotel'
,'The White Rock Hotel'
,'Blossomwell Resorts'
,'Hotel Happy springs'
,'FeetZing Hotel'
,'Hotel Lucia'
,'Dreamy Desert Suites'
,'Quest Hotel'
,'The Nines'
,'Everman'
,'Cedar Hotel'
,'The River Front Resort'
,'Hilton Garden Inn'
,'Radisson Hotel'
,'Americana Hotel'
,'The Watson Hotel'
,'Parker New York'
,'Towne Place Suites'
,'Quality Suites'
,'The Roosevelt Hotel'
,'SpiritFord'
,'Hotel Vitale'

,'Family Ties'
,'Proton Hotel'
,'Elite Peak'
,'Cotton House Hotel'
,'DeadFly Hotel'
,'Double Forest'
,'RedFlag Hotel'
,'The Sebastian Vail'
,'Scenic Solitude Resort'
,'Fiesto Hotel'
,'Jade Mountain'
,'The Palms Hotel Spa'
,'Blossomwell Resorts'
,'Fountainhead Reserve'
,'Fortune Inn & Suites'
,'Thundermine'
,'The Hoxton'
,'Raffel Hotel'
,'Triumph'
,'Coast Hotels'
,'Nationwide Motel'
,'Triple Creek Ranch'
,'Twice Happy Resorts'
,'Chestnut Tree Inn'
,'Spectra Hotel'


,'Elden Essa'
,'Regency Hotel'
,'Purple Orchid'
,'The Aluxor'
,'Resting Love Hotel'
,'Pearl Hotel'
,'Harborview Inn & Suites'
,'Waikiki Resort'
,'Neptune Hollywood Beach Resort'
,'Reefs Resort & Club'
,'Qualia'
,'Green Lushy Resorts'
,'Leamington Hotel'
,'Entrada Resort'
,'Southern Ocean Lodge'
,'Fresh Wave Resort & Spa'
,'Hotal Strata'
,'Signature San Francisco'
,'Inndigo Chill /Indigo Chill'
,'Hapuna Beach Suites'
,'Mandarin Oriental'
,'White Elephant Hotel'
,'Renaissance Hotels'
,'Residence Inn'
,'Grand & Epic'

,'The Enchanted Garden'
,'Grand Hotel'
,'The New View'
,'White Dove Hotels'
,'Waypoint'
,'Villa Florence'
,'Cabrillo Inn & Suites'
,'Hampton Inn & Suites'
,'The Cartwright Hotel'
,'Denali Perch Resort'
,'Royal Galaxy'
,'Four Seasons Hotel Gresham Palace'
,'Venture Hotel'
,'Classio Hotel'
,'Hotel Lemonade'
,'Homewood Suites'
,'The James New York'
,'Rodeway Inn'
,'The Maxwell'
,'Royal Place'
,'Aloft Chicago'
,'The Houstonian Hotel'
,'The Bay Club'
,'Embassy Suites'
,'Holiday Inn Express'

,'Harbor Court Hotel'
,'Rooftop Resort'
,'Staybridge Suites'
,'Candlewood Hotel'
,'Oxford Suites'
,'Super 8'
,'Sizzling inn'
,'London House'
,'Knights Inn'
,'Hotel Indigo'
,'Beachwalk Hotel'
,'Hotel Vertigo'
,'Row Hotel'
,'Peninsula Hotel'
,'Cassius Hotel'
,'Hotel Emblem'
,'Sea Horizon'
,'Hotel Mastic Marvell'
,'Holiday Inn Express'
,'Lexington'
,'Red Lion Hotel'
,'Green Acres'
,'Hotel deLuxe'
,'Inn of Chicago'
,'Crowne Plaza'


,'Four Seasons Resort'
,'Happy Stay'
,'Town and Country'
,'Quick Stop'
,'Inn Of Dreams'
,'Fountain Fun'
,'Olympus Hotel'
,'Enchanted Isles Hotel'
,'Hotel Diva'
,'Hotel Elite'
,'Sapphires Hotel'
,'The Greenwich Hotel'
,'The Jefferson'
,'Fortune House'
,'Hotel Bliss'
,'Hotel Triton'
,'Emerald Bay Inn'
,'The Nines'
,'Better and Better'
,'The Langham'
,'Dream Desert Hotel'
,'Night In Paradise'
,'Blue Moon'
,'Heritage Inn'
,'Hotel Rose'












]
