module.exports.categories =[
'Welding',
'Electrician',
'Plumbing',
'Carpentry',
'Construction management',
'Pipe-fitting',
'Machining',
'Computer-aided drafting',
'Network administration',
'Civil engineering tech',
'Hair dresser',
'Tailor',
'Biomedical engineering',
'Goldsmith',
'Gem cutter',
'Photography',
'Barbers',
'Steel erecting',
'Welding',
'Boilermaking',
'Millwright',
'Blacksmith',
'Gunsmith',
'Marquetarian',
'Farrier',
'Furniture making',
'Pewterer',
'Damascener',
'Laptop repair',
'Phone repair',
'Shoemaking',
'Massage',
'Watch repair',
'Catering',
'Printing',
'Generator repair',
'Chauffeur',
'Vigilante',
'Plumbing machine repair',
'Freezer repair'
]

